### ISSUE TITLE
Works good on arsenal or energy assault

### ISSUE THREAD

**Issue by FrostyDevLOL** [MarsQQ/Aimmy#11]

**Comment by FrostyDevLOL** [comment]
Question

**Comment by MarsQQ** [comment]
> Question

Got something to ask us?

- Nori

**Comment by FrostyDevLOL** [comment]
> > Question
> 
> Got something to ask us?
> 
> * Nori

The title

**Comment by MarsQQ** [comment]
> > > Question
> > 
> > 
> > Got something to ask us?
> > 
> > * Nori
> 
> The title

Oh! I thought you were just reporting that it works well on the game! 
Aimmy works pretty well on Arsenal from my experience, note that plays best when you tune your settings based on your experience. Changing the Minimum Confidence, Aim Offset, etc, can really improve your experience!

Unfortunately, I have never heard of Energy Assault before, so I can’t report whether it works well on that game. It doesn’t hurt to try though =)

- Nori

**Comment by FrostyDevLOL** [comment]
> > > > Question
> > > 
> > > 
> > > Got something to ask us?
> > > 
> > > * Nori
> > 
> > 
> > The title
> 
> Oh! I thought you were just reporting that it works well on the game! Aimmy works pretty well on Arsenal from my experience, note that plays best when you tune your settings based on your experience. Changing the Minimum Confidence, Aim Offset, etc, can really improve your experience!
> 
> Unfortunately, I have never heard of Energy Assault before, so I can’t report whether it works well on that game. It doesn’t hurt to try though =)
> 
> * Nori

Thanks for letting me know. I'm on my phone rn so I couldn't test it

**Comment by FrostyDevLOL** [comment]
Solved
