### ISSUE TITLE
What's better for arsenal aimmy or python?

### ISSUE THREAD

**Issue by FrostyDevLOL** [MarsQQ/Aimmy#13]
Python showcase vid: https://youtu.be/bx9rv9fUjqQ?si=vyAkloJK-isK9FxP

**Comment by FrostyDevLOL** [comment]
Sorry 2nd question I am too lazy to use the python one

**Comment by MarsQQ** [comment]
For Arsenal, the Python ColorBot is better, since it uses a much faster method to detect players and is also more accurate since it relies on the results given by the game itself. It, however, cannot be used on other games.

- Nori
