### ISSUE TITLE
Open Issue

### ISSUE THREAD

**Issue by skxddedv2** [MarsQQ/Aimmy#14]
opened task manager it opens for like 2 seconds then closes i have net 7.0.403 installed so i have no idea what the bug could be

**Comment by skxddedv2** [comment]
ui doesnt pop up also

**Comment by MarsQQ** [comment]
Hey!

Has Aimmy been extracted from the zip file?

- Nori

**Comment by LegoScripter** [comment]
The same thing is happening to me: Aimmy is extracted, and when opened, it appears in the task manager. It makes the mouse really slow and laggy and then closes.

**Comment by Babyhamsta** [comment]
Please test the newest release v1.1.0 - https://github.com/MarsQQ/Aimmy/releases/tag/v1.1.0
