### ISSUE TITLE
There was an error starting the ONNXModel

### ISSUE THREAD

**Issue by fastvariable** [MarsQQ/Aimmy#18]
![image](https://github.com/MarsQQ/Aimmy/assets/130872826/0dc35979-3333-4763-bef9-7a5cf3df3749)

**Comment by Babyhamsta** [comment]
Please type in dxdiag in the Windows Search and send a screenshot here of what info it returns.
Thank you!

**Comment by Babyhamsta** [comment]
Also please confirm that you see the DirectML.dll and onnxruntime.dll in the same folder as the exe.

**Comment by Alexplaysbk** [comment]
Same this is happening to me aswell should i send?

**Comment by Babyhamsta** [comment]
Please send a screenshot of dxdiag (you can find it via Windows Search) and confirm that you see the DirectML.dll and onnxruntime.dll in the same folder as the exe.

**Comment by LegoScripter** [comment]
My PC is really shitty but same error is happening
![image_2023-10-28_210144161](https://github.com/MarsQQ/Aimmy/assets/87584351/f61f0f3c-89b6-4fac-94c1-c6841cd98808)
![image_2023-10-28_210236785](https://github.com/MarsQQ/Aimmy/assets/87584351/ba8d2da7-3ff7-4511-90da-830d307174db)

**Comment by fastvariable** [comment]
damn it wont let me send an image

https://media.discordapp.net/attachments/1158716105314009169/1168073426620125244/image.png?ex=65507026&is=653dfb26&hm=78f9d10bb77897e9718dd9000187b9aa38ab00ac1e61c59c4d65ad1c5dcc6bda&=&width=509&height=230

**Comment by Babyhamsta** [comment]
It appears your system does support DirectX12 but might not support DirectML.
Can you send me a screenshot of your exe folder with all the dlls inside?

**Comment by kingsommar** [comment]
if not working download these following things (microsoft trust) 
![image](https://github.com/MarsQQ/Aimmy/assets/149288492/73c6612a-75a8-494f-9e29-29f71c78e37e)

**Comment by Babyhamsta** [comment]
I believe the fix is 2015-2019 vcredist. I have added it to our setup instructions: https://github.com/MarsQQ/Aimmy#setup
