### ISSUE TITLE
Literally aims next to the players

### ISSUE THREAD

**Issue by EbicSeal** [MarsQQ/Aimmy#20]
i was testing this in pf and it fucking aims next to the heads, ive tried literally everything with sensitivity and offsets and still nothing, confidence too, please use better images for the training model cuz this is awful.

also fix the circle being clickable and unfocussing the window.

**Comment by Babyhamsta** [comment]
I haven't experienced the FOV being clickable, it should work just like an overlay. There is nothing wrong with our training data all of it has been combed through and picked. You'll need to use the offsets to adjust the X/Y on the model. Note that offsets do have some issues at longer distances.

You are also more than welcome to download the source and test some modifications to see if you can make further enhancements. We don't owe you anything nor are we required to fix your bugs. This is an source available free to use software, so keep that in mind.
