### ISSUE TITLE
[ISSUE] roblox gets laggy and aimmy doesnt lock on

### ISSUE THREAD

**Issue by 311NNZ** [MarsQQ/Aimmy#21]
It drops frames (fps) and it doesnt really lock on when the keybind is hold.

Looking forward to this project though.

I have pretty shitty pc specs but more or less decent for roblox lol

Processor	AMD Athlon Silver 3050U with Radeon Graphics      2.30 GHz
RAM 4,00 GB (3,42 GB usable)
64x bits based OS

Sorry if my english is bad, im from spain and english is not my first language.

Cheers.

**Comment by 311NNZ** [comment]
I used both versions available and both have the same issue

**Comment by hitshoCodes** [comment]
Same here

**Comment by Babyhamsta** [comment]
AMD seems to have a real problem with DirectML which uses DirectX12. It only appears to affect AMD graphics cards. We are looking into other solutions but AMD hasn't really provided good support for Windows nor have they moved their ROCM or GraphXML over to Windows yet.

We will look to see what other fixes we can do for AMD but until those are released on Windows we don't have a lot of options.
