### ISSUE TITLE
MakeSense AI Issues

### ISSUE THREAD

**Issue by PericoSpart** [MarsQQ/Aimmy#23]
I have some images from Aimmy, I putted them on MakeSense.AI, made labels and then the boxes on the players with either Enemies or Friends. I exported to a zip YOLO format. What do I do now?

**Comment by NikoWiki** [comment]
what's your discord i can help

**Comment by PericoSpart** [comment]
.arcold @NikoWiki

**Comment by NikoWiki** [comment]
Added hogthewog

**Comment by Babyhamsta** [comment]
Please see the newest tut that I've recorded it has instructions for everything: https://www.youtube.com/watch?v=ozYzjS5p2H8
