### ISSUE TITLE
Can't select a model...

### ISSUE THREAD

**Issue by JustLeska** [MarsQQ/Aimmy#25]
![image](https://github.com/MarsQQ/Aimmy/assets/82216890/4336e1ca-57be-4df8-b4fb-711635b1d111)

Btw I am on Windows Sandbox

**Comment by Babyhamsta** [comment]
Please send a screenshot of dxdiag (you can find it via Windows Search) and confirm that you see the DirectML.dll and onnxruntime.dll in the same folder as the exe.

**Comment by JustLeska** [comment]
Sure!
![image](https://github.com/MarsQQ/Aimmy/assets/82216890/4311483b-53fa-4fc7-93e2-29bbcc24c24c)
![image](https://github.com/MarsQQ/Aimmy/assets/82216890/c1bf066a-972d-48db-9600-4e599d28bae4)
![image](https://github.com/MarsQQ/Aimmy/assets/82216890/2fd481af-17ba-4b55-b3cf-b2b284e28528)

Hope that helps :)

**Comment by Babyhamsta** [comment]
From the error message it appears the exe cannot find the onnxruntime.dll or DirectML.dll. Please ensure both dlls are in the same folder as the exe and that you've fully extracted the zip file from releases.

**Comment by JustLeska** [comment]
That is strange beacause I did...
