### ISSUE TITLE
Aim bug, aiming randomly on 1.1.1

### ISSUE THREAD

**Issue by K1xzy** [MarsQQ/Aimmy#27]
check the video out, lets see if we can fix it soon

1.0.0 doesnt seem to have this issue
EDIT: sorry for bad video quality, cannot upload more than 10MB on here

https://github.com/MarsQQ/Aimmy/assets/109889881/00b19440-fbbf-4a01-8717-a1fd2c7c14b8

**Comment by Anonymousperson0016** [comment]
Your mouse sensitivity is set to something too fast in aimmy. In this update higher = lower speed. So try putting that number up to around 0.7.

**Comment by K1xzy** [comment]
yeah your right, my bad i did not check that, thanks for letting me know

**Comment by Anonymousperson0016** [comment]
You're welcome!

**Comment by HandSomeNissan** [comment]
Hey, no matter what sens i put it still does this exact same thing. any help? @Anonymousperson0016

**Comment by HandSomeNissan** [comment]
Nevermind, my in game sens was just too high.

**Comment by Babyhamsta** [comment]
Closing ticket, user error.
