### ISSUE TITLE
error when choosing model

### ISSUE THREAD

**Issue by potatoman42o** [MarsQQ/Aimmy#28]
i get this error when i try to choose the pf model
![image](https://github.com/MarsQQ/Aimmy/assets/79148997/da8fbba0-10b9-45df-8837-6ea495427ec9)
And then it crashes

**Comment by Catplayz2011** [comment]
I have the same error :(

**Comment by Babyhamsta** [comment]
From the error message it appears the exe cannot find the onnxruntime.dll or DirectML.dll. Please ensure both dlls are in the same folder as the exe and that you've fully extracted the zip file from releases.

**Comment by potatoman42o** [comment]
![image](https://github.com/Babyhamsta/Aimmy/assets/79148997/1307a6c7-6b58-4e7e-960d-b73ab4d1fb89)
the dlls are there

**Comment by Babyhamsta** [comment]
Fix was added to Setup: https://github.com/Babyhamsta/Aimmy#setup

You need to install VCRedist 2015-2019 x64.

**Comment by potatoman42o** [comment]
thanks
