### ISSUE TITLE
Issue with selecting models.

### ISSUE THREAD

**Issue by Catplayz2011** [MarsQQ/Aimmy#29]
![image](https://github.com/MarsQQ/Aimmy/assets/144529766/e31d7d57-dd3c-41c5-9d3c-0f082b08468f)

I have read smth about the other issues and you have asked for a screenshot of dxdiag:

![image](https://github.com/MarsQQ/Aimmy/assets/144529766/ccc9b0cd-28d2-4960-b613-b17c38bc2dfe)

**Comment by Babyhamsta** [comment]
From the error message it appears the exe cannot find the onnxruntime.dll or DirectML.dll. Please ensure both dlls are in the same folder as the exe and that you've fully extracted the zip file from releases.
