### ISSUE TITLE
My mouse just teleports to top left screen when using aim aligner

### ISSUE THREAD

**Issue by T-byte-sketch** [MarsQQ/Aimmy#3]
It just makes my mouse go up to top left corner

**Comment by MarsQQ** [comment]
Hey!

I would like to ask what game + model you are using. 

It would also help to toggle first/third party aim if you're dealing with that.

Thanks!

- Nori

**Comment by Babyhamsta** [comment]
Here is a short tut on how to use it, it sounds like your Mouse Sensitivity is too high, try raising it to 0.19 or higher.
https://streamable.com/bd5zbf

**Comment by T-byte-sketch** [comment]
Nevermind it still occurs I've set the sensitivity lower and it still happens.

**Comment by MarsQQ** [comment]
> Nevermind it still occurs I've set the sensitivity lower and it still happens.
> 
> currently testing this on da hood and random avatar images from google.

Are you able to upload a screen recording of this issue so we can see what is going on?

It would be helpful to know what kind of GPU you're using 😊

**Comment by Babyhamsta** [comment]
> Nevermind it still occurs I've set the sensitivity lower and it still happens.
> 
> currently testing this on da hood and random avatar images from google.

Da hood is 3rd person aim no? Currently Aimmy does not support 3rd person aim. This is also why images on Google would be going to the top left corner as Aimmy attempts to offset from the center of the screen.

**Comment by T-byte-sketch** [comment]
It's a first person + third person game, you can zoom out if you want to play third person or zoom in for first person, I was testing this in first person and sometimes it won't even lock onto players and other times my mouse will flick out to the side not at the player of course.

**Comment by T-byte-sketch** [comment]
I did try nezur and it works fine so it's nothing wrong with my gpu which can handle it, also just tested the phantom forces model and it still happens (was using the configs in the video for reference).
