### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maik8326** [MarsQQ/Aimmy#31]
I have a question: why didn't you just make a discord server if you were already getting several friend requests? Ever thought of just making a discord server? And the second question, would a video be created that explains exactly how to make a model yourself? Then all my questions would already be answered.

**Comment by HandSomeNissan** [comment]
I agree with you on the discord server

Babyhamsta already uploaded a video on how to make a model: https://youtu.be/ozYzjS5p2H8

**Comment by MarsQQ** [comment]
Hey!

We haven't made a discord yet because we aren't sure how it should be made. We were considering converting WEAO into the Aimmy server, but those plans have yet to be established. So for now, everything will be done here :)

- Nori
