### ISSUE TITLE
How to train propperly / Enemy / Allies

### ISSUE THREAD

**Issue by Catplayz2011** [MarsQQ/Aimmy#34]
How can i make it that it only locking on enemy's i dont know how i can train it

**Comment by Babyhamsta** [comment]
Right now it should be trained on Enemies which should mean that it attempts to avoid teammates at all costs. If you want you can train your own model to see if you get better performance. Check out our YT tut on training and labeling images: https://github.com/MarsQQ/Aimmy#how-do-i-train-my-own-model
