### ISSUE TITLE
Issues with creating a Model ( I watched the video)

### ISSUE THREAD

**Issue by Catplayz2011** [MarsQQ/Aimmy#36]
https://github.com/MarsQQ/Aimmy/assets/144529766/1b18983f-03be-475b-89dc-3fc4794c0e38

After following every step you can clearly see that i didnt work, I tried to run it as administrator before and i had the same reults.

pip install ultralytics : **Did no work** as you can see on the video 
Train cmd : **Did no work too** --> Video
JUST in case the cmd is wrong : yolo task-detect mode-train imgsz-640 data-CustomCharackterPath.yaml epochs-1000 batch-16 name-Universalv1
Im trying to solve this problem for 4 hours ?

[+] Isnt there an software were you just need to put in the pics and lables and it will autotrain for you ?

👍  thanks !

**Comment by Babyhamsta** [comment]
Ensure that you have Python installed, pip is apart of Python: https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe

**Comment by Catplayz2011** [comment]
**Python** is fully **_installed_** just in case ! I used the **[REPAIR]** option on Python. And I went to my **### windows app settings** And searched for **python** and I found it 👍 

Video :  

https://github.com/MarsQQ/Aimmy/assets/144529766/f4cc5def-f828-476d-8fac-5f94b3212ef7

**Comment by Babyhamsta** [comment]
You may need to uninstall and reinstall, ensure you have these settings selected and that you are installing pip with it.
![image](https://github.com/MarsQQ/Aimmy/assets/22938086/e92bd8bb-088a-4a50-927e-3cb271b69956)

**Comment by Babyhamsta** [comment]
That's fine, if you open it as admin it already selects that option by default.

**Comment by Catplayz2011** [comment]
It worked and it didn't worked...


Uploading bandicam 2023-10-30 15-37-51-183.mp4…

**Comment by Babyhamsta** [comment]
It looks like your pip is bugging out, did you restart after installing? You can try starting fresh by doing these two commands:

1. `pip freeze > requirements.txt`
2. `pip uninstall -r requirements.txt -y`

and then trying to reinstall Ultralytics via this command:
`pip install ultralytics --no-cache --force-reinstall`

**Comment by Catplayz2011** [comment]
Restart my pc ? After installing Python ?

![image](https://github.com/MarsQQ/Aimmy/assets/144529766/cb4f175e-1a5a-4fc1-9228-c23d0bfddc68)

**Comment by Babyhamsta** [comment]
That means that nothing is installed, you'll need to reinstall Ultralytics now.

**Comment by Babyhamsta** [comment]
Again I would recommend starting fully fresh, meaning I would uninstall any Python program you have and then restart. I would then reinstall Python while adding it to the PATH and reboot again.

I would then rerun the pip install for Ultralytics.

**Comment by Catplayz2011** [comment]
So i uninstalled every python programm rebooted, installed the latest python version, rebooted then I opened my cmd and typed in : pip install ultralytics

again the same problem...

**Comment by Babyhamsta** [comment]
There are tools where you can train online but this isn't support for those or issues with installing Ultralytics, you'll need to open an issue request on their github or do research into the errors you are having.

**Comment by Catplayz2011** [comment]
So I should go to unltralytic's Github ? And open an issue ?

**Comment by Babyhamsta** [comment]
Yes, they might be able to assist you further and better than I can on their install via pip.
