### ISSUE TITLE
[Feature Request] Auto Trainer

### ISSUE THREAD

**Issue by Xeon-E** [MarsQQ/Aimmy#4]
As inspired by the "Collect Data While Playing" feature, a "Auto Trainer Mode" would be performance intensive but let anyone create their own model quickly and easily while not having to take snap shots of characters. While this mode is in use, it takes pictures of what might be detected as an enemy, and stored. From there, when told so, the data storing process will stop. Then the AI takes it time with each picture to identify what is actually the target, this is then stored. From there, it updates a current data model or makes a new one, which will be selected before the initial data collection process. Thus making model creating easy and Aimmy actually universal.

**Comment by MarsQQ** [comment]
Hey!

I don't think we will probably do this. Training the AI Models alone takes a while and is incredibly resource intensive, and while our models are pretty good, they're not perfect and susceptible to false positives and false negatives.

We still provide the web model though, it's a great option to speed up labeling times :D

@Babyhamsta may have something to add.

- Nori

**Comment by Babyhamsta** [comment]
Lord I would love to see something like but unfortunately other than Auto Distill there is no such tool to auto label and upgrade the AI's performance at least not with how we are running this model. We currently use a YOLOv8 model formatted to Onnx. YOLO is You Only Look Once and it's an Object Detection AI. If we used something like a NEAT network or another type of AI we may be able to have it learn while you play but not with the Object Detection model we currently have it has to have data submitted to it, which for us comes in the form of labeled images of enemies.
