### ISSUE TITLE
[Feature Request] [Resource intensive] Allow more screenshots to be taken per second (more smooth aim)

### ISSUE THREAD

**Issue by Imagnir** [MarsQQ/Aimmy#5]
It would be nice if there is a way to increase the screenshots and ai process per second, to maybe have a smoother aim.
I have a good computer and it would be nice to do that, as of right now, it is very choppy and it feels weird. (I have a 144hz screen)
(I know it will be resource intensive, it would only be something for good computers, such as a toggle that warns that it will use alot of resources, or idk)

**Comment by T-byte-sketch** [comment]
Would love to see this be implemented as an optional feature would be really helpful and would really take the aimbot to a whole new level.

**Comment by MarsQQ** [comment]
Hey!

This would be a great idea! Unfortunately, with how these functions seem to be written (from my eyes), it does not seem to be possible to do this. There's nothing (from what I can tell) that seems to artificially slow the process down. Though @Babyhamsta will definitely have a better answer than I do!

- Nori

**Comment by Babyhamsta** [comment]
Speeding up the process that is all dependent on your system's performance. I've gone back through and optimized my code as much as possible to allow the AI to perform the best. I can review things a bit more to see what I can squeeze out of it but right now it should always try to run at 100%.

Please let us know more details by providing a description of your computer so we can better judge on how performance is on other systems.

- CPU
- GPU
- Memory
- SSD/HDD
- Windows 10/11

**Comment by Babyhamsta** [comment]
Please test the newest release v1.1.0 - https://github.com/MarsQQ/Aimmy/releases/tag/v1.1.0

It has a lot faster detection speeds.
