### ISSUE TITLE
UI Not Appearing Upon Execution

### ISSUE THREAD

**Issue by Glory223** [MarsQQ/Aimmy#6]
As stated in the title, after clicking on the .exe file nothing happens other than it making my mouse move incredibly slow. Yes I did follow steps and installed the correct .NET runtime.

**Comment by Imagnir** [comment]
I also had that, I just needed to wait. As directly when opening the program it loads a model, thus lagging.
I really think the program should not load any model when launched until specified by the user.

**Comment by MarsQQ** [comment]
Hey!

I'll experiment with these ideas, though it would most likely be a non-default toggleable option because it wouldn't exactly be user-friendly.

- Nori

**Comment by Babyhamsta** [comment]
Ensure you have fully extracted the ZIP and that the bin folder is accessible to the exe. If the exe is unable to see and load the models it can cause that.

**Comment by Glory223** [comment]
Forgot to come back and say that Imaginr's reply helped, I just wasn't waiting long enough for it to load lol. But thank you anyway.

**Comment by Babyhamsta** [comment]
Please test the newest release v1.1.0 - https://github.com/MarsQQ/Aimmy/releases/tag/v1.1.0
