### ISSUE TITLE
[REQUEST] Training Files For Model Refining & Testing

### ISSUE THREAD

**Issue by RealCalumPlays** [MarsQQ/Aimmy#7]
Hey there,

I want to train the model on my GPU Enabled machine but I don't see any kind of training data. Is there a way I can get a copy of the training files? I don't want to make private models just test out my datasets and send the results to you guys

Thanks.

**Comment by Babyhamsta** [comment]
We aren't sure if we want to release the source images for training, We have the web model which could help you with labeling those images but we are worried competitors would use our training data for profit with their system and we want things to stay free and open source here.

- Hamsta

**Comment by MarsQQ** [comment]
> We aren't sure if we want to release the source images for training, We have the web model which could help you with labeling those images but we are worried competitors would use our training data for profit with their system and we want things to stay free and open source here.
> 
>     * Hamsta

If you would like to contribute to our dataset though, we will gladly take your image and labels through Discord :D

- Nori

**Comment by RealCalumPlays** [comment]
> We aren't sure if we want to release the source images for training, We have the web model which could help you with labeling those images but we are worried competitors would use our training data for profit with their system and we want things to stay free and open source here.
> 
> * Hamsta

I dont want the source images I just want the training files so I can train locally.

**Comment by RealCalumPlays** [comment]
> > We aren't sure if we want to release the source images for training, We have the web model which could help you with labeling those images but we are worried competitors would use our training data for profit with their system and we want things to stay free and open source here.
> > ```
> > * Hamsta
> > ```
> 
> If you would like to contribute to our dataset though, we will gladly take your image and labels through Discord :D
> 
> * Nori

Hmu with your discord

**Comment by Xeon-E** [comment]
> Hey there,
> 
> I want to train the model on my GPU Enabled machine but I don't see any kind of training data. Is there a way I can get a copy of the training files? I don't want to make private models just test out my datasets and send the results to you guys
> 
> Thanks.

On this note, what would be cool is a website or repo that can be contributed too with people and their own models. For example the Chronus Zen community has their own GPC script library and community, so the same could be applied to Aimmy.

**Comment by RealCalumPlays** [comment]
**EDIT:**

I have found out how to train myself so this can be closed if needed but the commenter above me does have a good point.

**Comment by Babyhamsta** [comment]
> > We aren't sure if we want to release the source images for training, We have the web model which could help you with labeling those images but we are worried competitors would use our training data for profit with their system and we want things to stay free and open source here.
> > 
> > * Hamsta
> 
> I dont want the source images I just want the training files so I can train locally.
> 
> Im not looking to release anything I just want to make a couple specialized models for games I play.

That is why we released the Web Model, it allows you to use the model to help label images and thus train your own or provide those images to us for further training of our models.

You can see more details here: https://github.com/MarsQQ/Aimmy#what-is-the-web-model
