### ISSUE TITLE
(Question) Is aimmy undetected to anticheats like Vanguard?

### ISSUE THREAD

**Issue by T-byte-sketch** [MarsQQ/Aimmy#8]
I was planning on using public images and labels for valorant to make a model, but as you might know vanguard detects 99% of any fake mouse movement or simulated triggers on the users pc.

**Comment by Babyhamsta** [comment]
There are ways to get around this but it normally involves running the AI off the computer and passing images from the PC to a another machine. We don't use an extremely secure lib for mouse movements but there are always other options with macro mouses and ect.

**Comment by Xeon-E** [comment]
> There are ways to get around this but it normally involves running the AI off the computer and passing images from the PC to a another machine. We don't use an extremely secure lib for mouse movements but there are always other options with macro mouses and ect.
